name: Data Fetching
on: 
  push:
  schedule:
    - cron: "5 21 * * *"
  workflow_dispatch:

jobs:
  Fetch-Route-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crawling resources (Python)
        run: |
          python main.py
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install NodeJS dependencies
        run: |
          npm i puppeteer
      - name: Crawling resources (NodeJS)
        run: |
          node main.js
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
            file-path: data/*
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
            branch: data
