name: Data Fetching
on: 
  push:
  schedule:
    - cron: "5 21 * * *"
  workflow_dispatch:

jobs:
  Fetch-Route-Data:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'data'
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'
            architecture: 'x64'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crawling resources (Python)
        run: |
          python main.py
      - name: Setup NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install NodeJS dependencies
        run: |
          npm i puppeteer
      - name: Crawling resources (NodeJS)
        run: |
          node main.js
      - name: Update resources
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            file_pattern: 'data/**/*'
            commit_message: 'Update resources'
            branch: 'data'
            commit_options: '--no-verify'
            
